"""Check release identity and clean-wheel imports (Python 3.11+; no dependencies)."""

import argparse
import ast
import email
import json
import re
import subprocess
import tarfile
import zipfile
from pathlib import Path

import tomllib


def validate_versions(version: str, runtime: str, tag: str) -> None:
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version):
        raise ValueError("Only stable three-component release versions are allowed")
    if runtime != version or tag != "v" + version:
        raise ValueError("Release tag, source and runtime versions must match")


def source_identity(root: Path) -> tuple[str, str, str]:
    project = tomllib.loads((root / "pyproject.toml").read_text())["project"]
    name, version = project["name"], project["version"]
    module = name.replace("-", "_")
    tree = ast.parse((root / "src" / module / "__init__.py").read_text())
    runtime = next(
        ast.literal_eval(node.value)
        for node in tree.body
        if isinstance(node, ast.Assign)
        and any(isinstance(target, ast.Name) and target.id == "__version__" for target in node.targets)
    )
    return name, version, runtime


def check_artifacts(dist: Path, name: str, version: str) -> None:
    wheels, sources = list(dist.glob("*.whl")), list(dist.glob("*.tar.gz"))
    if len(wheels) != 1 or len(sources) != 1 or len(list(dist.iterdir())) != 2:
        raise ValueError("dist must contain exactly one wheel and one source distribution")
    with zipfile.ZipFile(wheels[0]) as wheel:
        if any("__pycache__/" in item or item.endswith(".pyc") for item in wheel.namelist()):
            raise ValueError("Generated bytecode found in wheel")
        metadata = [item for item in wheel.namelist() if item.endswith(".dist-info/METADATA")]
        if len(metadata) != 1:
            raise ValueError("Wheel must contain exactly one package metadata record")
        wheel_meta = email.message_from_bytes(wheel.read(metadata[0]))
    with tarfile.open(sources[0]) as source:
        records = [
            member
            for member in source.getmembers()
            if member.name.count("/") == 1 and member.name.endswith("/PKG-INFO")
        ]
        if len(records) != 1:
            raise ValueError("Source archive must contain exactly one root package metadata record")
        stream = source.extractfile(records[0])
        if stream is None:
            raise ValueError("Source package metadata is not a file")
        source_meta = email.message_from_bytes(stream.read())
    for metadata in (wheel_meta, source_meta):
        canonical = re.sub(r"[-_.]+", "-", metadata["Name"] or "").lower()
        if canonical != name or metadata["Version"] != version:
            raise ValueError("Artifact name/version does not match source")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--dist", type=Path)
    parser.add_argument("--installed-python", type=Path)
    args = parser.parse_args()
    name, version, runtime = source_identity(Path(__file__).resolve().parents[1])
    validate_versions(version, runtime, args.tag)
    if args.dist:
        check_artifacts(args.dist, name, version)
    if args.installed_python:
        code = (
            "import importlib,importlib.metadata,json,pathlib,sys;"
            f"m=importlib.import_module({name.replace('-', '_')!r});"
            f"print(json.dumps([importlib.metadata.version({name!r}),m.__version__,"
            "str(pathlib.Path(m.__file__).resolve()),str(pathlib.Path(sys.prefix).resolve())]))"
        )
        installed, runtime, module_path, prefix = json.loads(
            subprocess.check_output([str(args.installed_python.absolute()), "-I", "-c", code], text=True)
        )
        validate_versions(version, runtime, args.tag)
        if installed != version or not Path(module_path).is_relative_to(Path(prefix)):
            raise ValueError("Clean environment did not import the expected installed wheel")
    print(f"Validated {name} {version} against {args.tag}")


if __name__ == "__main__":
    main()
